### ISSUE TITLE
On dragging  super-splitter, text elements get selected automatically.

### ISSUE THREAD

**Issue by shljk** [super-elements/super-splitter#1]
On dragging  `super-splitter` left to right or vice-versa .The text written in workspace and title-bar  get selected automatically. Please see screencast below :point_down: 

![super-splitter](https://cloud.githubusercontent.com/assets/18029294/18428506/fc25f050-78eb-11e6-98eb-35779482af82.gif)

**Comment by gaurav21r** [comment]
This seems to be an issue with `preventSelection` which was not ported over from https://github.com/polymer/core-splitter
